dist: xenial                    # ubuntu 16.04

language: cpp
compiler: g++

before_install: sudo apt-get update -qq
install: export CXX="g++-5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libboost-all-dev

before_script:
  - git fetch origin master:remotes/origin/master
  - git fetch origin develop:remotes/origin/develop
        
script:
  - cmake .
  - make -j

notifications:
  on_success: never
  on_failure: never
